legacy_layout=false
horizontal
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_power
vram
cpu_stats
cpu_temp
cpu_mhz
ram
fps
frametime=1
frame_timing=1
gpu_name
vulkan_driver
resolution
fps_limit=0
show_fps_limit
font_size=20
background_alpha=0.4
position=top-left
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
