# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi


# Put your fun stuff here.
export PATH="$HOME/.local/bin:$PATH"

# purple astral@host, dim path (Synthwave #b967ff)
PS1='\[\e[1;38;2;185;103;255m\]\u@\h\[\e[0;38;2;122;73;132m\] \w \[\e[1;38;2;185;103;255m\]\$\[\e[0m\] '
