# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS=" -march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"



MAKEOPTS="-j20 -l20"

FEATURES="parallel-fetch parallel-install getbinpkg binpkg-request-signature candy"

VIDEO_CARDS="amdgpu radeonsi"

INPUT_DEVICES="libinput"

USE="vulkan pipewire wayland X -pulseaudio"

ABI_X86="64 32"

ACCEPT_LICENSE="*"


# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="https://ca.mirrors.cicku.me/gentoo/ \
    https://gentoo.iro.umontreal.ca/gentoo/ \
    https://gentoo.mirrors.ovh.net/gentoo-distfiles/ \
    https://elara.ca.ext.planetunix.net/pub/gentoo/ \
    https://mirror.reenigne.net/gentoo/ \
    http://gentoo.mirrors.tera-byte.com/ \
    https://mirror.csclub.uwaterloo.ca/gentoo-distfiles/"
GRUB_PLATFORMS="efi-64"
